from random import randint #AQUI EU IMPORTO DA BIBLIOTECA random A FUNÇÃO RANDINT(gera número inteiros aleatórios)

def carregar_lista(): #AQUI EU CRIO UMA FUNÇÃO QUE PRA RETORNAR UMA LISTA CARREGADA.
  lista = [] #AQUI EU CRIO UMA LISTA VAZIA.
  for c in range(15): #AQUI EU USO O LAÇO DE REPETIÇÃO FOR DE 15 VEZES.
    lista.append(randint(0,50))#ENTÃO 15 VEZES VAI SER ADICIONADO NA LISTA DE NOME lista UM NÚMERO INTEIRO ALEATÓRIO.
  return lista #USO O return PRA RETORNAR A VARIÁVEL DE NOME lista.

ch = carregar_lista()#AQUI EU CHAMO A FUNÇÃO carregar_lista.

def ler_maior(ch): #AQUI EU CRIO A FUNÇÃO ler_maior QUE RECEBE UM PARÂMETRO(ch) QUE É JUSTAMENTE O RETORNO DA FUNÇÃO carregar_lista.
  maior = -99999 #CRIEI ESSA VARIÁVEL PRA FAZER A COMPARAÇÃO DO MAIOR NÚMERO, USEI UM VALOR BEM PEQUENO(-99999) PARA QUE QUALQUER PRIMEIRA ENTRADA SEJA VERDADEIRAMENTE MAIOR.
  posicao = ch.index(max(ch)) #AQUI EU USO O .index QUE ME RETORNA A POSIÇÃO DE UM ELEMENTO.
  for c in ch: #AQUI EU PERCORRO O PARÂMETRO ch(QUE É UMA LISTA).
    if c > maior: #AQUI EU FAÇO A COMPARAÇÃO DE CADA ELEMENTO DENTRO DA LISTA ch COM A VARIÁVEL maior.
      maior = c #MAIOR RECEBE VARIÁVEL c(ELEMENTO DA LISTA) CASO ELE SEJA MAIOR DO QUE A VARIÁVEL maior.
  return f'MAIOR==> {maior}\nPOSIÇÃO DO MAIOR==> {posicao}' #AQUI EU RETORNO UMA TUPLA(O NÚMERO MAIOR E A POSIÇÃO DELE)

print(ch) # AQUI EU PRINTO A LISTA GERADA(ch)
ch1 = ler_maior(ch)#AQUI EU CHAMO A FUNÇÃO ler_maior QUE TEM PARÂMETRO ch(LISTA)
print(ch1) #AQUI EU PRINTO O RETORNO DA FUNÇÃO QUE FICA DENTRO DA VÁRIAVEL ch1.